// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkiStore.Data;

namespace SkiStore.Migrations.SkiStoreProductDb
{
    [DbContext(typeof(SkiStoreProductDbContext))]
    [Migration("20190222191959_firstSeed")]
    partial class firstSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SkiStore.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category");

                    b.Property<string>("Description");

                    b.Property<string>("ImageURL");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<int>("Quantity");

                    b.Property<string>("SKU");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Skis",
                            Price = 300m,
                            Quantity = 0
                        },
                        new
                        {
                            ID = 2,
                            Name = "Helmet",
                            Price = 150m,
                            Quantity = 0
                        },
                        new
                        {
                            ID = 3,
                            Name = "Goggles",
                            Price = 60m,
                            Quantity = 0
                        },
                        new
                        {
                            ID = 4,
                            Name = "Poles",
                            Price = 100m,
                            Quantity = 0
                        },
                        new
                        {
                            ID = 5,
                            Name = "Boots",
                            Price = 200m,
                            Quantity = 0
                        },
                        new
                        {
                            ID = 6,
                            Name = "Jacket",
                            Price = 100m,
                            Quantity = 0
                        },
                        new
                        {
                            ID = 7,
                            Name = "Pants",
                            Price = 100m,
                            Quantity = 0
                        },
                        new
                        {
                            ID = 8,
                            Name = "Gloves",
                            Price = 40m,
                            Quantity = 0
                        },
                        new
                        {
                            ID = 9,
                            Name = "Flask",
                            Price = 20m,
                            Quantity = 0
                        },
                        new
                        {
                            ID = 10,
                            Name = "Buff",
                            Price = 40m,
                            Quantity = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
